### ISSUE TITLE
Hi everyone. Got the traceback problem again.

### ISSUE THREAD

**Issue by johnpiers** [codeezer/livescore-cli#15]
Hi everyone. Got the traceback problem again. 
```
Traceback (most recent call last):
  File "/usr/local/bin/livescore", line 60, in <module>
    main()
  File "/usr/local/bin/livescore", line 33, in main
    lsprint.table(lsweb.get_table(URL[k][1]), k)
  File "/opt/livescore-cli/lib/lsprint.py", line 129, in table
    team_name = each_row[1]
IndexError: string index out of range
```

_Originally posted by @johnpiers in https://github.com/codeezer/livescore-cli/issues/14#issuecomment-1115013774_

**Comment by codeezer** [comment]
We have refactored project, some of the functionality might not be working as expected.
