### ISSUE TITLE
Traceback when trying to run livescore

### ISSUE THREAD

**Issue by johnpiers** [codeezer/livescore-cli#21]
Is this thing still relevant? I've never got it to work, all I get is this.  Thanks.

> Traceback (most recent call last):
>   File "/usr/local/bin/livescore", line 50, in <module>
>     main()
>   File "/usr/local/bin/livescore", line 32, in main
>     table = get_table(cname, event_type)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/johnpiers/.livescore-cli/lib/lsweb.py", line 133, in get_table
>     table = parse_table(soup)
>             ^^^^^^^^^^^^^^^^^
>   File "/home/johnpiers/.livescore-cli/lib/lsweb.py", line 117, in parse_table
>     body = lt.find('tbody')
>            ^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'find'

**Comment by johnpiers** [comment]
Still nothing, I'm guessing that this is going nowhere. Cheers.
